version: '2'

services:
  dai-rabbitmq:
    network_mode: host
    image: rabbitmq:3.7-management
    container_name: dai-rabbitmq
    environment:
      - RABBITMQ_NODE_IP="0.0.0.0"
    restart: always
